GEMINI_API_KEY_NAME="GEMINI_DEV_API_KEY"
GEMINI_MODEL="gemini-2.0-flash"
TEMP_RESPONSE_FILE_NAME="./temp/temp-response.json"
RESPONSE_SCRIPT_FILE_NAME="./temp/response-script.sh"
ROOT_DIRECTORY="/home/afzal/Desktop/flow-cli-testing"